// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfo2OBkhpuXbAgVzF2Kn93vWvFkDvVXKQ',
    appId: '1:411691750871:web:9a0e65c874d7a62b256792',
    messagingSenderId: '411691750871',
    projectId: 'ehadir-ff9a9',
    authDomain: 'ehadir-ff9a9.firebaseapp.com',
    storageBucket: 'ehadir-ff9a9.firebasestorage.app',
    measurementId: 'G-QS73K1J0MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRqu319holGRHF03O2-kIz3AAc0czYqX4',
    appId: '1:411691750871:android:50275a671a908a3d256792',
    messagingSenderId: '411691750871',
    projectId: 'ehadir-ff9a9',
    storageBucket: 'ehadir-ff9a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5IYZ0YjGe4gHJH4ssl8rD1sS-K0PTbH0',
    appId: '1:411691750871:ios:037c5c0c641c0e69256792',
    messagingSenderId: '411691750871',
    projectId: 'ehadir-ff9a9',
    storageBucket: 'ehadir-ff9a9.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5IYZ0YjGe4gHJH4ssl8rD1sS-K0PTbH0',
    appId: '1:411691750871:ios:037c5c0c641c0e69256792',
    messagingSenderId: '411691750871',
    projectId: 'ehadir-ff9a9',
    storageBucket: 'ehadir-ff9a9.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfo2OBkhpuXbAgVzF2Kn93vWvFkDvVXKQ',
    appId: '1:411691750871:web:e23c4c39c76ffd6e256792',
    messagingSenderId: '411691750871',
    projectId: 'ehadir-ff9a9',
    authDomain: 'ehadir-ff9a9.firebaseapp.com',
    storageBucket: 'ehadir-ff9a9.firebasestorage.app',
    measurementId: 'G-YGYPML0PD0',
  );
}
